/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFuzzy;

import javax.swing.JButton;
import net.sourceforge.jFuzzyLogic.FIS;
import net.sourceforge.jFuzzyLogic.plot.JDialogFis;

/**
 *
 * @author dionmax
 */
public class JPanelFuzzy extends javax.swing.JFrame {

    /**
     * Creates new form JPanelFuzzy
     */
    private static int vidaPersonagem = 50;
    private static int vidaAdversario = 50;
    private static int turnoJogador = 8;

    String fileName = "/home/dionmax/Downloads/Faculdade/7P/IA/Fuzzy/JavaFuzzy_v2/TrabalhoDionmaxAllan.fcl";
    FIS fis = FIS.load(fileName, true);
    JDialogFis dialogoFIS = new JDialogFis(fis);
     
    public JPanelFuzzy() {
        initComponents();
        
        jRadioButton_Personagem.setSelected(true);
        
        fis.setVariable("Saude_Personagem", 50);
        fis.setVariable("Saude_Adversario", 50);
        fis.setVariable("Turno", 8);
        fis.evaluate();

    }

    public void runGame() {
        fis.setVariable("Saude_Personagem", vidaPersonagem);
        fis.setVariable("Saude_Adversario", vidaAdversario);
        fis.setVariable("Turno", turnoJogador);
        fis.evaluate();
        dialogoFIS.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Turno = new javax.swing.ButtonGroup();
        jSlideMonstro = new javax.swing.JSlider();
        jSliderPersonagem = new javax.swing.JSlider();
        jRadioButton_Personagem = new javax.swing.JRadioButton();
        jRadioButton_Adversario = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSlideMonstro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlideMonstroStateChanged(evt);
            }
        });

        jSliderPersonagem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPersonagemStateChanged(evt);
            }
        });

        Turno.add(jRadioButton_Personagem);
        jRadioButton_Personagem.setText("Personagem");
        jRadioButton_Personagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PersonagemActionPerformed(evt);
            }
        });

        Turno.add(jRadioButton_Adversario);
        jRadioButton_Adversario.setText("Adversário");
        jRadioButton_Adversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AdversarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton_Personagem)
                        .addGap(18, 18, 18)
                        .addComponent(jSliderPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton_Adversario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSlideMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSliderPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jRadioButton_Personagem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlideMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Adversario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderPersonagemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPersonagemStateChanged
        vidaPersonagem = jSliderPersonagem.getValue();
        runGame();
    }//GEN-LAST:event_jSliderPersonagemStateChanged

    private void jSlideMonstroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlideMonstroStateChanged
        vidaAdversario = jSlideMonstro.getValue();
        runGame();
    }//GEN-LAST:event_jSlideMonstroStateChanged

    private void jRadioButton_PersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PersonagemActionPerformed
        turnoJogador = 8;
        runGame();
    }//GEN-LAST:event_jRadioButton_PersonagemActionPerformed

    private void jRadioButton_AdversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AdversarioActionPerformed
        turnoJogador = 2;
        runGame();
    }//GEN-LAST:event_jRadioButton_AdversarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPanelFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPanelFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPanelFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPanelFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPanelFuzzy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Turno;
    private javax.swing.JRadioButton jRadioButton_Adversario;
    private javax.swing.JRadioButton jRadioButton_Personagem;
    private javax.swing.JSlider jSlideMonstro;
    private javax.swing.JSlider jSliderPersonagem;
    // End of variables declaration//GEN-END:variables
}
